name: Run R Script

on:
  workflow_dispatch:

jobs:
  run-r:
    runs-on: ubuntu-latest
    environment: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Cache R packages #cache packages to make future runs faster
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev libssl-dev libxml2-dev

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("aws.s3", "dplyr"), repos = "https://cloud.r-project.org")'

      - name: Run R script
        env:
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY }}
        run: Rscript utils/coc/upload_BC_Box.R
